In [1]:
import numpy as np

arr = np.zeros((2, 2))
print(arr)


[[0. 0.]
 [0. 0.]]


In [2]:
import numpy as np

arr = np.ones((4, 2))
print(arr)


[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [3]:
import numpy as np

arr = np.full((3, 3), 7)
print(arr)


[[7 7 7]
 [7 7 7]
 [7 7 7]]


In [4]:
import numpy as np

original = np.array([[3, 5, 7],
                     [1, 2, 4]])

new_array = np.zeros_like(original)
print(new_array)


[[0 0 0]
 [0 0 0]]


In [5]:
import numpy as np

original = np.array([[4, 8, 12],
                     [2, 6, 10]])

new_array = np.ones_like(original)
print(new_array)


[[1 1 1]
 [1 1 1]]


In [6]:
import numpy as np

new_list = [1, 2, 3, 4]

arr = np.array(new_list)
print(arr)


[1 2 3 4]


In [7]:
import numpy as np

arr = np.arange(10, 50)
print(arr)


[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [8]:
import numpy as np

arr = np.arange(9).reshape(3, 3)
print(arr)


[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [9]:
import numpy as np

identity_matrix = np.eye(3)
print(identity_matrix)


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [10]:
import numpy as np

arr = np.random.random(30)

print("Array:")
print(arr)

mean_value = arr.mean()
print("\nMean of the array:", mean_value)


Array:
[2.27859827e-01 5.38069490e-01 5.31309761e-01 7.93686290e-01
 6.53886380e-01 1.41661634e-01 5.52114743e-01 5.76268395e-01
 3.09070627e-01 8.07280237e-01 7.53673524e-01 1.93088869e-02
 9.96498639e-01 9.81936399e-01 5.05518282e-01 8.73504841e-01
 2.17296034e-01 9.24962689e-01 3.64427671e-02 2.87103404e-01
 8.72759048e-01 9.76488305e-01 2.70806591e-01 4.70106106e-01
 7.53943839e-04 6.65616231e-01 8.18645844e-01 2.83217509e-01
 4.43623808e-01 2.23033484e-01]

Mean of the array: 0.5250834573756593


In [12]:
import numpy as np
arr = np.random.random((10, 10))

print("Array:")
print(arr)
min_value = arr.min()
max_value = arr.max()

print("\nMinimum value:", min_value)
print("Maximum value:", max_value)


Array:
[[0.71505955 0.72762461 0.70580414 0.03062681 0.52789247 0.45446266
  0.41869276 0.00279637 0.52458641 0.0111557 ]
 [0.95283046 0.1876881  0.6870421  0.92766128 0.0182766  0.83614343
  0.9166897  0.71693858 0.43376778 0.87113795]
 [0.32649121 0.66159293 0.51508524 0.99621368 0.1075303  0.41454859
  0.25149981 0.8037694  0.81977929 0.64222005]
 [0.95252285 0.37352241 0.53176955 0.10010501 0.92533065 0.69957903
  0.57218211 0.8621484  0.21732933 0.01135746]
 [0.86475242 0.76694228 0.26392018 0.35560278 0.10519104 0.93540926
  0.40595876 0.55846134 0.51807011 0.66708415]
 [0.21842747 0.33928268 0.03604569 0.67814917 0.54542737 0.72009794
  0.69383656 0.06204264 0.35552551 0.29861851]
 [0.89364866 0.76833316 0.71262097 0.42681682 0.32224365 0.04440775
  0.36984482 0.03536137 0.41441981 0.8948212 ]
 [0.95883731 0.11226169 0.88380088 0.69020313 0.70748275 0.48791485
  0.15003994 0.89379422 0.48774281 0.73188669]
 [0.02610562 0.07408453 0.2675242  0.31812155 0.72821649 0.94706005
  0.3

In [13]:
import numpy as np


arr = np.zeros(10, dtype=int)

arr[4] = 1

print(arr)


[0 0 0 0 1 0 0 0 0 0]


In [14]:
import numpy as np

arr = np.array([1, 2, 0, 0, 4, 0])

reversed_arr = arr[::-1]
print(reversed_arr)


[0 4 0 0 2 1]


In [15]:
import numpy as np

arr = np.ones((5, 5), dtype=int)
arr[1:-1, 1:-1] = 0

print(arr)


[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


In [16]:
import numpy as np

checkerboard = np.zeros((8, 8), dtype=int)
checkerboard[1::2, ::2] = 1
checkerboard[::2, 1::2] = 1

print(checkerboard)


[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [17]:
import numpy as np

x = np.array([[1, 2],
              [3, 5]])

y = np.array([[5, 6],
              [7, 8]])

v = np.array([9, 10])
w = np.array([11, 12])


In [18]:
add_xy = x + y
print(add_xy)


[[ 6  8]
 [10 13]]


In [19]:
sub_xy = x - y
print(sub_xy)


[[-4 -4]
 [-4 -3]]


In [20]:
mul_x = x * 3
print(mul_x)


[[ 3  6]
 [ 9 15]]


In [21]:
square_x = x ** 2
print(square_x)


[[ 1  4]
 [ 9 25]]


In [22]:
dot_vw = np.dot(v, w)
print(dot_vw)


219


In [23]:
concat_xy = np.concatenate((x, y), axis=0)
print(concat_xy)


[[1 2]
 [3 5]
 [5 6]
 [7 8]]


In [25]:
np.concatenate((x, v), axis=0)


ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

In [26]:
v_reshaped = v.reshape(1, 2)
concat_fix = np.concatenate((x, v_reshaped), axis=0)
print(concat_fix)


[[ 1  2]
 [ 3  5]
 [ 9 10]]


In [28]:
A_inv = np.linalg.inv(A)
result = A @ A_inv
print(result)


[[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]


In [29]:
AB = A @ B
BA = B @ A

print("AB =\n", AB)
print("BA =\n", BA)


AB =
 [[23 13]
 [51 29]]
BA =
 [[36 44]
 [13 16]]


In [30]:
left = (A @ B).T
right = B.T @ A.T

print(left)
print(right)


[[23 51]
 [13 29]]
[[23 51]
 [13 29]]


In [ ]:
2x − 3y +  z = −1
x  −  y + 2z = −3
3x +  y −  z =  9


In [31]:
A = np.array([[2, -3,  1],
              [1, -1,  2],
              [3,  1, -1]])

B = np.array([[-1],
              [-3],
              [ 9]])


In [32]:
A_inv = np.linalg.inv(A)
X = A_inv @ B
print(X)


[[ 2.]
 [ 1.]
 [-2.]]


In [33]:
X = np.linalg.solve(A, B)
print(X)


[[ 2.]
 [ 1.]
 [-2.]]
